// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: microserv2.proto

package grpc.eBank.payments;

public final class PaymentServiceImpl {
  private PaymentServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payments_PaymentRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payments_PaymentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payments_UpdateBalanceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payments_UpdateBalanceResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020microserv2.proto\022\010payments\"H\n\016PaymentR" +
      "equest\022\023\n\013accountFrom\030\001 \001(\t\022\021\n\taccountTo" +
      "\030\002 \001(\t\022\016\n\006amount\030\003 \001(\001\"C\n\025UpdateBalanceR" +
      "esponse\022\021\n\taccountTo\030\001 \001(\t\022\027\n\017acknowledg" +
      "ement\030\003 \001(\t2i\n\016PaymentService\022W\n\024sendMul" +
      "tiplePayments\022\030.payments.PaymentRequest\032" +
      "\037.payments.UpdateBalanceResponse\"\000(\0010\001B+" +
      "\n\023grpc.eBank.paymentsB\022PaymentServiceImp" +
      "lP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_payments_PaymentRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_payments_PaymentRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payments_PaymentRequest_descriptor,
        new java.lang.String[] { "AccountFrom", "AccountTo", "Amount", });
    internal_static_payments_UpdateBalanceResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_payments_UpdateBalanceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payments_UpdateBalanceResponse_descriptor,
        new java.lang.String[] { "AccountTo", "Acknowledgement", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
