// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: microserv2.proto

package grpc.eBank.payments;

/**
 * Protobuf type {@code payments.UpdateBalanceResponse}
 */
public  final class UpdateBalanceResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:payments.UpdateBalanceResponse)
    UpdateBalanceResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use UpdateBalanceResponse.newBuilder() to construct.
  private UpdateBalanceResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UpdateBalanceResponse() {
    accountTo_ = "";
    acknowledgement_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private UpdateBalanceResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            accountTo_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            acknowledgement_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.eBank.payments.PaymentServiceImpl.internal_static_payments_UpdateBalanceResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.eBank.payments.PaymentServiceImpl.internal_static_payments_UpdateBalanceResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.eBank.payments.UpdateBalanceResponse.class, grpc.eBank.payments.UpdateBalanceResponse.Builder.class);
  }

  public static final int ACCOUNTTO_FIELD_NUMBER = 1;
  private volatile java.lang.Object accountTo_;
  /**
   * <code>string accountTo = 1;</code>
   */
  public java.lang.String getAccountTo() {
    java.lang.Object ref = accountTo_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      accountTo_ = s;
      return s;
    }
  }
  /**
   * <code>string accountTo = 1;</code>
   */
  public com.google.protobuf.ByteString
      getAccountToBytes() {
    java.lang.Object ref = accountTo_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      accountTo_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ACKNOWLEDGEMENT_FIELD_NUMBER = 3;
  private volatile java.lang.Object acknowledgement_;
  /**
   * <code>string acknowledgement = 3;</code>
   */
  public java.lang.String getAcknowledgement() {
    java.lang.Object ref = acknowledgement_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      acknowledgement_ = s;
      return s;
    }
  }
  /**
   * <code>string acknowledgement = 3;</code>
   */
  public com.google.protobuf.ByteString
      getAcknowledgementBytes() {
    java.lang.Object ref = acknowledgement_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      acknowledgement_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getAccountToBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, accountTo_);
    }
    if (!getAcknowledgementBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, acknowledgement_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getAccountToBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, accountTo_);
    }
    if (!getAcknowledgementBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, acknowledgement_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.eBank.payments.UpdateBalanceResponse)) {
      return super.equals(obj);
    }
    grpc.eBank.payments.UpdateBalanceResponse other = (grpc.eBank.payments.UpdateBalanceResponse) obj;

    boolean result = true;
    result = result && getAccountTo()
        .equals(other.getAccountTo());
    result = result && getAcknowledgement()
        .equals(other.getAcknowledgement());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ACCOUNTTO_FIELD_NUMBER;
    hash = (53 * hash) + getAccountTo().hashCode();
    hash = (37 * hash) + ACKNOWLEDGEMENT_FIELD_NUMBER;
    hash = (53 * hash) + getAcknowledgement().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.eBank.payments.UpdateBalanceResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.eBank.payments.UpdateBalanceResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.eBank.payments.UpdateBalanceResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.eBank.payments.UpdateBalanceResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.eBank.payments.UpdateBalanceResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.eBank.payments.UpdateBalanceResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.eBank.payments.UpdateBalanceResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.eBank.payments.UpdateBalanceResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.eBank.payments.UpdateBalanceResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.eBank.payments.UpdateBalanceResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.eBank.payments.UpdateBalanceResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.eBank.payments.UpdateBalanceResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.eBank.payments.UpdateBalanceResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code payments.UpdateBalanceResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:payments.UpdateBalanceResponse)
      grpc.eBank.payments.UpdateBalanceResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.eBank.payments.PaymentServiceImpl.internal_static_payments_UpdateBalanceResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.eBank.payments.PaymentServiceImpl.internal_static_payments_UpdateBalanceResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.eBank.payments.UpdateBalanceResponse.class, grpc.eBank.payments.UpdateBalanceResponse.Builder.class);
    }

    // Construct using grpc.eBank.payments.UpdateBalanceResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      accountTo_ = "";

      acknowledgement_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.eBank.payments.PaymentServiceImpl.internal_static_payments_UpdateBalanceResponse_descriptor;
    }

    @java.lang.Override
    public grpc.eBank.payments.UpdateBalanceResponse getDefaultInstanceForType() {
      return grpc.eBank.payments.UpdateBalanceResponse.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.eBank.payments.UpdateBalanceResponse build() {
      grpc.eBank.payments.UpdateBalanceResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.eBank.payments.UpdateBalanceResponse buildPartial() {
      grpc.eBank.payments.UpdateBalanceResponse result = new grpc.eBank.payments.UpdateBalanceResponse(this);
      result.accountTo_ = accountTo_;
      result.acknowledgement_ = acknowledgement_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.eBank.payments.UpdateBalanceResponse) {
        return mergeFrom((grpc.eBank.payments.UpdateBalanceResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.eBank.payments.UpdateBalanceResponse other) {
      if (other == grpc.eBank.payments.UpdateBalanceResponse.getDefaultInstance()) return this;
      if (!other.getAccountTo().isEmpty()) {
        accountTo_ = other.accountTo_;
        onChanged();
      }
      if (!other.getAcknowledgement().isEmpty()) {
        acknowledgement_ = other.acknowledgement_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      grpc.eBank.payments.UpdateBalanceResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (grpc.eBank.payments.UpdateBalanceResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object accountTo_ = "";
    /**
     * <code>string accountTo = 1;</code>
     */
    public java.lang.String getAccountTo() {
      java.lang.Object ref = accountTo_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        accountTo_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string accountTo = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAccountToBytes() {
      java.lang.Object ref = accountTo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        accountTo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string accountTo = 1;</code>
     */
    public Builder setAccountTo(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      accountTo_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string accountTo = 1;</code>
     */
    public Builder clearAccountTo() {
      
      accountTo_ = getDefaultInstance().getAccountTo();
      onChanged();
      return this;
    }
    /**
     * <code>string accountTo = 1;</code>
     */
    public Builder setAccountToBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      accountTo_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object acknowledgement_ = "";
    /**
     * <code>string acknowledgement = 3;</code>
     */
    public java.lang.String getAcknowledgement() {
      java.lang.Object ref = acknowledgement_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        acknowledgement_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string acknowledgement = 3;</code>
     */
    public com.google.protobuf.ByteString
        getAcknowledgementBytes() {
      java.lang.Object ref = acknowledgement_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        acknowledgement_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string acknowledgement = 3;</code>
     */
    public Builder setAcknowledgement(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      acknowledgement_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string acknowledgement = 3;</code>
     */
    public Builder clearAcknowledgement() {
      
      acknowledgement_ = getDefaultInstance().getAcknowledgement();
      onChanged();
      return this;
    }
    /**
     * <code>string acknowledgement = 3;</code>
     */
    public Builder setAcknowledgementBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      acknowledgement_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:payments.UpdateBalanceResponse)
  }

  // @@protoc_insertion_point(class_scope:payments.UpdateBalanceResponse)
  private static final grpc.eBank.payments.UpdateBalanceResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.eBank.payments.UpdateBalanceResponse();
  }

  public static grpc.eBank.payments.UpdateBalanceResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UpdateBalanceResponse>
      PARSER = new com.google.protobuf.AbstractParser<UpdateBalanceResponse>() {
    @java.lang.Override
    public UpdateBalanceResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new UpdateBalanceResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<UpdateBalanceResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UpdateBalanceResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.eBank.payments.UpdateBalanceResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

