// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: microserv.proto

package grpc.eBank.login;

public interface LoginResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:login.LoginResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string responseMessage = 1;</code>
   */
  java.lang.String getResponseMessage();
  /**
   * <code>string responseMessage = 1;</code>
   */
  com.google.protobuf.ByteString
      getResponseMessageBytes();

  /**
   * <code>bool logIn = 3;</code>
   */
  boolean getLogIn();
}
