// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: microserv1.proto

package grpc.eBank.account;

public interface TransactionRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:account.TransactionRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string account = 1;</code>
   */
  java.lang.String getAccount();
  /**
   * <code>string account = 1;</code>
   */
  com.google.protobuf.ByteString
      getAccountBytes();

  /**
   * <code>int32 number = 2;</code>
   */
  int getNumber();
}
