// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: microserv1.proto

package grpc.eBank.account;

public interface TransactionsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:account.TransactionsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *entity represents the organisation/individual the account interacted with in the transaction
   * </pre>
   *
   * <code>string entity = 1;</code>
   */
  java.lang.String getEntity();
  /**
   * <pre>
   *entity represents the organisation/individual the account interacted with in the transaction
   * </pre>
   *
   * <code>string entity = 1;</code>
   */
  com.google.protobuf.ByteString
      getEntityBytes();

  /**
   * <pre>
   *amount credited/debited in the transaction
   * </pre>
   *
   * <code>double amount = 2;</code>
   */
  double getAmount();
}
