// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: microserv1.proto

package grpc.eBank.account;

public interface UpdatedBalanceRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:account.UpdatedBalanceRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string account = 1;</code>
   */
  java.lang.String getAccount();
  /**
   * <code>string account = 1;</code>
   */
  com.google.protobuf.ByteString
      getAccountBytes();

  /**
   * <code>double balance = 2;</code>
   */
  double getBalance();
}
