// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: microserv1.proto

package grpc.eBank.account;

public interface UpdatedBalanceResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:account.UpdatedBalanceResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double accumulatedBalance = 1;</code>
   */
  double getAccumulatedBalance();
}
