// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: microserv2.proto

package grpc.eBank.payments;

public interface UpdateBalanceResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:payments.UpdateBalanceResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string accountTo = 1;</code>
   */
  java.lang.String getAccountTo();
  /**
   * <code>string accountTo = 1;</code>
   */
  com.google.protobuf.ByteString
      getAccountToBytes();

  /**
   * <code>float balance = 2;</code>
   */
  float getBalance();
}
