// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: microserv1.proto

package grpc.eBank.account;

public final class BalanceServiceImpl {
  private BalanceServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_account_TransactionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_account_TransactionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_account_TransactionsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_account_TransactionsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_account_UpdatedBalanceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_account_UpdatedBalanceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_account_UpdatedBalanceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_account_UpdatedBalanceResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020microserv1.proto\022\007account\"5\n\022Transacti" +
      "onRequest\022\017\n\007account\030\001 \001(\t\022\016\n\006number\030\002 \001" +
      "(\005\"6\n\024TransactionsResponse\022\016\n\006entity\030\001 \001" +
      "(\t\022\016\n\006amount\030\002 \001(\001\"9\n\025UpdatedBalanceRequ" +
      "est\022\017\n\007account\030\001 \001(\t\022\017\n\007balance\030\002 \001(\001\"4\n" +
      "\026UpdatedBalanceResponse\022\032\n\022accumulatedBa" +
      "lance\030\001 \001(\0012\300\001\n\016BalanceService\022[\n\031reques" +
      "tTransactionHistory\022\033.account.Transactio" +
      "nRequest\032\035.account.TransactionsResponse\"" +
      "\0000\001\022Q\n\ngetBalance\022\036.account.UpdatedBalan" +
      "ceRequest\032\037.account.UpdatedBalanceRespon" +
      "se\"\000(\001B*\n\022grpc.eBank.accountB\022BalanceSer" +
      "viceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_account_TransactionRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_account_TransactionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_account_TransactionRequest_descriptor,
        new java.lang.String[] { "Account", "Number", });
    internal_static_account_TransactionsResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_account_TransactionsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_account_TransactionsResponse_descriptor,
        new java.lang.String[] { "Entity", "Amount", });
    internal_static_account_UpdatedBalanceRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_account_UpdatedBalanceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_account_UpdatedBalanceRequest_descriptor,
        new java.lang.String[] { "Account", "Balance", });
    internal_static_account_UpdatedBalanceResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_account_UpdatedBalanceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_account_UpdatedBalanceResponse_descriptor,
        new java.lang.String[] { "AccumulatedBalance", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
